version: '3'

services:
  mkdocs:
    # image: ghcr.io/peaceiris/mkdocs-material:latest
    image: mkdocsboiler
    container_name: mkdocsboiler
    ports:
      - 8000:8000
    volumes:
      - ${PWD}:/root
    stdin_open: true
    tty: true
    command:
      - "mkdocs"
      - "serve"
      - "--dev-addr=0.0.0.0:8000"
      - "--config-file"
      - "./mkdocs-config.yml"
